version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: sfl_nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - sfl_network

  php:
    image: php:8.1-fpm
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: sfl_app
    volumes:
      - .:/var/www/html
    networks:
      - sfl_network

networks:
  sfl_network:
    driver: bridge